project:
  type: book
  output-dir: docs

book:
  title: "Population Ecology"
  subtitle: "A gentle introduction using R"
  author: 
    - name: "Erlend B. Nilsen"
      orcid: 0000-0002-5119-8331
  repo-url: https://github.com/ErlendNilsen/PopEcology_NordUni_booklet
  repo-branch: main
  repo-actions: [edit, issue]
  cover-image: cover2.jpg
  
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: The_organism.qmd
      chapters:
      - Adaptation_Selection.qmd
      - Life_histories.qmd
      - Movement_ecology.qmd
    
    - part: The_population.qmd
      chapters:
      - Population_growth.qmd
      - Density_dependence.qmd
      - Age_structured.qmd
      - Metapopulation_dynamics.qmd
      
    - part: Species_interactions.qmd
      chapters: 
        - Predation.qmd
        - Competition.qmd
        - Non_lethal.qmd
    
    - part: Applied_population_ecology.qmd
      chapters: 
        - Harvesting.qmd
        
    - References.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

author-meta: "Erlend B. Nilsen, Nord University"
